version: '2.1'

services:
  msl8r:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: hmctspublic.azurecr.io/labs/msl8r
    ports:
      - $SERVER_PORT:$SERVER_PORT
